language: python
python:
  - "3.7"

# command to install dependencies
install:
  - pip install -r requirements.txt

script:
  - mkdir -p /media
  - cd recipe_store
  - python manage.py test && flake8
